### ISSUE TITLE
Update json

### ISSUE THREAD

**Issue by dacrhu** [totaljs/node-sqlagent#22]
Hi,

my document like:

{
email: "xyz@xyz.com",
status: {
active: true,
created: "20170106"
}
}

If I use update method to status.active then sqlagent rewrite the full status (delete created field).
How can I update only active field?

Thank you,
David

**Comment by molda** [comment]
Hi, i think that builder doesn't support updating of a property inside of nested object.
If you are using this
`builder.set({ status: { active: false }});`
or this
`builder.set('status', { active: false });`
then it will replace whole `status` object since it creates following query
`{ $set: { status: { active: false }}}`  this is like doing `status = { active: false }`
but you need either
`{ $set: { 'status.active': false }}` this is like doing `status.active = false;` so other props of status object remains the same
 or
`{ status: { $set: { active: false }}}`
This might do what you need
`builder.raw({ status: { $set: { active: false }}});`
or
`builder.raw({ $set: { 'status.active': false }});`
or
`builder.set('status.active': false);`

Hope it helps.

**Comment by dacrhu** [comment]
builder.set('status.active': false);
working fine :)

Thank you!
